using Bogus;

namespace Eisk.Domains.TestData
{
    using Entities;
    using Enums;
    using System;
    using Test.Core.DataGen;

    public class EmployeeDataFactory:EntityDataFactory<Employee>
    {
        public override Employee Factory_Entity(Action<Employee>? action = null)
        {
            var employee = base.Factory_Entity( e =>
            {
                AssignEmployee(e);

                //supporting custom overrides from user
                action?.Invoke(e);
            });

            return employee;
        }

        void AssignEmployee(Employee employee)
        {
            var faker = new Faker();
            
            employee.Id = 0;
            employee.ReportsTo = null;
            employee.ReportsToId = null;
            employee.Subordinates = null;

            employee.TitleOfCourtesy = faker.PickRandom<TitleOfCourtesy>();
            employee.FirstName = faker.Person.FirstName;
            employee.LastName = faker.Person.LastName;
            employee.BirthDate = faker.Date.Past();

            var fakerAddress = faker.Address;
            employee.Address = new ValueObjects.Address
            {
                AddressLine = fakerAddress.StreetAddress(),
                City = fakerAddress.City(),
                PostalCode = fakerAddress.ZipCode(),
                Region = fakerAddress.State(),
                Country = fakerAddress.Country(),
            };

            employee.HireDate = faker.Date.Future();
            employee.Title = null;
            employee.Phone = faker.Person.Phone;
            //employee.Extension = null;

            employee.Photo = null;

            //employee.Notes: to be auto-generated by the underlying framework
        }

    }
}
