using Bogus;

namespace Eisk.Domains.TestData
{
    using Domains.Entities;
    using Domains.Enums;
    using Test.Core.DataGen;

    public class EmployeeDataFactory:EntityDataFactory<Employee>
    {
        public Employee Factory_Entity()
        {
            return base.Factory_Entity(AssignEmployee);
        }

        void AssignEmployee(Employee employee)
        {
            var faker = new Faker();

            employee.Id = 0;
            employee.ReportsTo = null;
            employee.ReportsToId = null;
            employee.Subordinates = null;

            employee.TitleOfCourtesy = faker.PickRandom<TitleOfCourtesy>();
            employee.FirstName = faker.Person.FirstName;
            employee.LastName = faker.Person.LastName;
            employee.BirthDate = faker.Date.Past();

            var fakerAddress = faker.Address;
            employee.Address = new Domains.ValueObjects.Address
            {
                AddressLine = fakerAddress.StreetAddress(),
                City = fakerAddress.City(),
                PostalCode = fakerAddress.ZipCode(),
                Region = fakerAddress.State(),
                Country = fakerAddress.Country(),
            };

            employee.HireDate = faker.Date.Future();
            employee.Title = null;
            employee.Phone = faker.Person.Phone;
            employee.Extension = null;

            employee.Photo = null;

            //employee.Notes: to be auto-generated by the underlying framework
        }

    }
}
